USE trainViewer;

INSERT INTO Country (country_name, alpha2_code) VALUES
('Afghanistan','AF'),
('Albania','AL'),
('Algeria','DZ'),
('Andorra','AD'),
('Angola','AO'),
('Anguilla','AI'),
('Antartide','AQ'),
('Antigua e Barbuda','AG'),
('Arabia Saudita','SA'),
('Argentina','AR'),
('Armenia','AM'),
('Aruba','AW'),
('Australia','AU'),
('Austria','AT'),
('Azerbaigian','AZ'),
('Bahamas','BS'),
('Bahrein','BH'),
('Bangladesh','BD'),
('Barbados','BB'),
('Belgio','BE'),
('Belize','BZ'),
('Benin','BJ'),
('Bermuda','BM'),
('Bhutan','BT'),
('Bielorussia','BY'),
('Birmania','MM'),
('Bolivia','BO'),
('Bosnia ed Erzegovina','BA'),
('Botswana','BW'),
('Brasile','BR'),
('Brunei','BN'),
('Bulgaria','BG'),
('Burkina Faso','BF'),
('Burundi','BI'),
('Cambogia','KH'),
('Camerun','CM'),
('Canada','CA'),
('Capo Verde','CV'),
('Ciad','TD'),
('Cile','CL'),
('Cina','CN'),
('Cipro','CY'),
('Città'' del Vaticano','VA'),
('Colombia','CO'),
('Comore','KM'),
('Corea del Nord','KP'),
('Corea del Sud','KR'),
('Costa d''Avorio','CI'),
('Costa Rica','CR'),
('Croazia','HR'),
('Cuba','CU'),
('Cura','CW'),
('Danimarca','DK'),
('Dominica','DM'),
('Ecuador','EC'),
('Egitto','EG'),
('El Salvador','SV'),
('Emirati Arabi Uniti','AE'),
('Eritrea','ER'),
('Estonia','EE'),
('Etiopia','ET'),
('Figi','FJ'),
('Filippine','PH'),
('Finlandia','FI'),
('Francia','FR'),
('Gabon','GA'),
('Gambia','GM'),
('Georgia','GE'),
('Georgia del Sud e isole Sandwich meridionali','GS'),
('Germania','DE'),
('Ghana','GH'),
('Giamaica','JM'),
('Giappone', 'JP'),
('Gibilterra','GI'),
('Gibuti','DJ'),
('Giordania','JO'),
('Grecia','GR'),
('Grenada','GD'),
('Groenlandia','GL'),
('Guadalupa','GP'),
('Guam','GU'),
('Guatemala','GT'),
('Guernsey','GG'),
('Guinea','GN'),
('Guinea-Bissau','GW'),
('Guinea Equatoriale','GQ'),
('Guyana','GY'),
('Guyana francese','GF'),
('Haiti','HT'),
('Honduras','HN'),
('Hong Kong','HK'),
('India','IN'),
('Indonesia','ID'),
('Iran','IR'),
('Iraq','IQ'),
('Irlanda','IE'),
('Islanda','IS'),
('Isola Bouvet','BV'),
('Isola di Man','IM'),
('Isola di Natale','CX'),
('Isola Norfolk','NF'),
('Isole ','AX'),
('Isole BES','BQ'),
('Isole Cayman','KY'),
('Isole Cocos (Keeling)','CC'),
('Isole Cook','CK'),
('Isole Falkland','FK'),
('Isole Heard e McDonald','HM'),
('Isole Marianne Settentrionali','MP'),
('Isole Marshall','MH'),
('Isole minori esterne degli Stati Uniti','UM'),
('Isole Pitcairn','PN'),
('Isole Salomone','SB'),
('Isole Vergini britanniche','VG'),
('Isole Vergini americane','VI'),
('Israele','IL'),
('Italia','IT'),
('Jersey','JE'),
('Kazakistan','KZ'),
('Kenya','KE'),
('Kirghizistan','KG'),
('Kiribati','KI'),
('Kuwait','KW'),
('Laos','LA'),
('Lesotho','LS'),
('Lettonia','LV'),
('Libano','LB'),
('Liberia','LR'),
('Libia','LY'),
('Liechtenstein','LI'),
('Lituania','LT'),
('Lussemburgo','LU'),
('Macao','MO'),
('Macedonia','MK'),
('Madagascar','MG'),
('Malawi','MW'),
('Malesia','MY'),
('Maldive','MV'),
('Mali','ML'),
('Malta','MT'),
('Marocco','MA'),
('Martinica','MQ'),
('Mauritania','MR'),
('Mauritius','MU'),
('Mayotte','YT'),
('Messico','MX'),
('Micronesia','FM'),
('Moldavia','MD'),
('Mongolia','MN'),
('Montenegro','ME'),
('Montserrat','MS'),
('Mozambico','MZ'),
('Namibia','NA'),
('Nauru','NR'),
('Nepal','NP'),
('Nicaragua','NI'),
('Niger','NE'),
('Nigeria','NG'),
('Niue','NU'),
('Norvegia','NO'),
('Nuova Caledonia','NC'),
('Nuova Zelanda','NZ'),
('Oman','OM'),
('Paesi Bassi','NL'),
('Pakistan','PK'),
('Palau','PW'),
('Palestina','PS'),
('Panam','PA'),
('Papua Nuova Guinea','PG'),
('Paraguay','PY'),
('Per','PE'),
('Polinesia Francese','PF'),
('Polonia','PL'),
('Porto Rico','PR'),
('Portogallo','PT'),
('Monaco','MC'),
('Qatar','QA'),
('Regno Unito','GB'),
('RD del Congo','CD'),
('Rep. Ceca','CZ'),
('Rep. Centrafricana','CF'),
('Rep. del Congo','CG'),
('Rep. Dominicana','DO'),
('Riunione','RE'),
('Romania','RO'),
('Ruanda','RW'),
('Russia','RU'),
('Sahara Occidentale','EH'),
('Saint Kitts e Nevis','KN'),
('Santa Lucia','LC'),
('Sant''Elena, Ascensione e Tristan da Cunha','SH'),
('Saint Vincent e Grenadine','VC'),
('Saint-Barth','BL'),
('Saint-Martin','MF'),
('Saint-Pierre e Miquelon','PM'),
('Samoa','WS'),
('Samoa Americane','AS'),
('San Marino','SM'),
('Senegal','SN'),
('Serbia','RS'),
('Seychelles','SC'),
('Sierra Leone','SL'),
('Singapore','SG'),
('Sint Maarten','SX'),
('Siria','SY'),
('Slovacchia','SK'),
('Slovenia','SI'),
('Somalia','SO'),
('Spagna','ES'),
('Sri Lanka','LK'),
('Stati Uniti','US'),
('Sudafrica','ZA'),
('Sudan','SD'),
('Sudan del Sud','SS'),
('Suriname','SR'),
('Svalbard e Jan Mayen','SJ'),
('Svezia','SE'),
('Svizzera','CH'),
('Swaziland','SZ'),
('Taiwan','TW'),
('Tagikistan','TJ'),
('Tanzania', 'TZ'),
('Terre australi e antartiche francesi','TF'),
('Territorio britannico dell''oceano Indiano','IO'),
('Thailandia','TH'),
('Timor Est','TL'),
('Togo','TG'),
('Tokelau','TK'),
('Tonga','TO'),
('Trinidad e Tobago','TT'),
('Tunisia','TN'),
('Turchia','TR'),
('Turkmenistan','TM'),
('Turks e Caicos','TC'),
('Tuvalu','TV'),
('Ucraina','UA'),
('Uganda','UG'),
('Ungheria','HU'),
('Uruguay','UY'),
('Uzbekistan','UZ'),
('Vanuatu','VU'),
('Venezuela','VE'),
('Vietnam','VN'),
('Wallis e Futuna','WF'),
('Yemen','YE'),
('Zambia','ZM'),
('Zimbabwe','ZW');
